### ISSUE TITLE
Build Errors (08/10/2018)

### ISSUE THREAD

**Issue by Kcr19** [Kcr19/mender_gcp_ota_demo#11]
Build script needs updated paths based on the new repo layout changes:

https://github.com/Kcr19/mender_gcp_ota_demo/blob/mender-gcp/image/mender-gcp-build.sh

Path below needs updates

- [ -d meta-gcp-iot ] || git clone https://github.com/Kcr19/mender_gcp_ota_demo.git

- bitbake-layers add-layer -F ../meta-gcp-iot/image/meta-gcp-iot

**Comment by drewmoseley** [comment]
Looks like the fix from @Kcr19 for this works.

**Comment by ptone** [comment]
@Kcr19  can you verify and close if true?

**Comment by Kcr19** [comment]
Updated script with the changes works. Closing this.
