### ISSUE TITLE
update reliance on gcs sample locations to git

### ISSUE THREAD

**Issue by ptone** [Kcr19/mender_gcp_ota_demo#21]
in server setup:

gsutil cp gs://mender-gcp/mender_gcp_scripts/prod.yml ./

Should be replace with a reference to a github raw content

**Comment by Kcr19** [comment]
Updated the server setup script to use prod.yml in Git instead of GCS - https://github.com/Kcr19/mender_gcp_ota_demo/blob/mender-gcp/server/mender_server_install.sh
