### ISSUE TITLE
bake in project and registry id

### ISSUE THREAD

**Issue by ptone** [Kcr19/mender_gcp_ota_demo#5]
these need to be incorporated into the build, these then still need to be read in from the python script

These could be put in /etc/gcp as a simple ini or json file, then read in by the python script

currently the python agent that starts on boot has these hardcoded

**Comment by drewmoseley** [comment]
A first pass at this is now in https://github.com/Kcr19/mender_gcp_ota_demo/pull/10

**Comment by ptone** [comment]
This seems to work as intended - I have some fixes for the agent code with some syntax and line ending issues
