### ISSUE TITLE
finish the recipe for the python iot agent

### ISSUE THREAD

**Issue by ptone** [Kcr19/mender_gcp_ota_demo#6]
the start of the script, and the systemd file are already here:
https://github.com/Kcr19/mender_gcp_ota_demo/tree/mender-gcp/image/meta-gcp-iot/recipes-gcp/mender-google-activation-agent

need the .bb files

**Comment by drewmoseley** [comment]
This is available here: https://github.com/Kcr19/mender_gcp_ota_demo/pull/10

**Comment by ptone** [comment]
Closing this for the bb and layer parts
